# Generated by Django 4.2.3 on 2023-08-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ending',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
