# Generated by Django 4.2.3 on 2023-08-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_ending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='started_at',
            field=models.TimeField(),
        ),
    ]
