# Generated by Django 4.2.3 on 2023-08-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_post_updated_at_alter_post_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='started_at',
            field=models.CharField(max_length=30),
        ),
    ]
