# Generated by Django 4.2.3 on 2023-08-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_updated_at_alter_post_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='started_at',
            field=models.TimeField(blank=True),
        ),
    ]
