# Generated by Django 4.2.3 on 2023-08-13 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0013_alter_post_follow_post_alter_post_follow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
