# Generated by Django 4.2.3 on 2023-08-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_delete_post_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '구인공고'},
        ),
    ]
