# Generated by Django 4.2.3 on 2023-08-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_post_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hits',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
