# Generated by Django 4.2.3 on 2023-07-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_choice1', models.BooleanField(blank=True, default=False)),
                ('question_choice2', models.BooleanField(blank=True, default=False)),
                ('question_choice3', models.BooleanField(blank=True, default=False)),
                ('question_choice4', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
