# Generated by Django 4.2.3 on 2023-07-21 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_choice1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_choice2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_choice3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_choice4',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(blank=True, max_length=20)),
                ('choice2', models.CharField(blank=True, max_length=20)),
                ('choice3', models.CharField(blank=True, max_length=20)),
                ('choice4', models.CharField(blank=True, max_length=20)),
                ('question_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.question')),
            ],
        ),
    ]
