# Generated by Django 4.2.3 on 2023-07-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_question_question_choice1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='choice3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='choice4',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
