# Generated by Django 4.2.3 on 2023-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_remove_question_answer_remove_question_choice1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_text',
            new_name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='question_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
