# Generated by Django 4.2.3 on 2023-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_rename_question_text_choice_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_complete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
