# Generated by Django 4.2.3 on 2023-07-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_man',
            field=models.BooleanField(default=False),
        ),
    ]
