# Generated by Django 4.2.3 on 2023-07-25 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_old_man'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='old_man',
        ),
        migrations.RemoveField(
            model_name='user',
            name='volunteer',
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer', models.BooleanField(default=False)),
                ('old_man', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
