# Generated by Django 4.2.3 on 2023-07-25 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_old_man_remove_user_volunteer_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Old_man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_man', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='old_man',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.volunteer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='old_man',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.old_man'),
            preserve_default=False,
        ),
    ]
