# Generated by Django 4.2.3 on 2023-07-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_needed_man_volunteer_user_needed_and_more'),
        ('accounts', '0006_rename_old_man_needed_man_and_more'),
    ]

    operations = [
    ]
