# Generated by Django 4.2.3 on 2023-07-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20230725_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='needed',
        ),
        migrations.DeleteModel(
            name='Needed_man',
        ),
    ]
