# Generated by Django 4.2.3 on 2023-07-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Alone',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
