# Generated by Django 4.2.3 on 2023-08-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checking',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
